config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :videos, only: [:show, :index], param: :slug
  resources :events, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :comments, only: [:show, :index] do
    resources :comments, only: [:show, :index, :create]
  end
  resources :galleries, only: [:show, :index], param: :slug
  resources :employees, only: :index
  root 'posts#home'
  get '/blog' => 'posts#index'
  get '/team' => 'employees#index'

  namespace :admin do
    root 'dashboards#index'
    resources :galleries, param: :slug do
      resources :gallery_images
    end
    resources :events, param: :slug do
      resources :comments
    end
    resources :categories
    resources :posts, param: :slug do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
    resources :users
    resources :videos, param: :slug
    resources :galleries, param: :slug
    resources :employees
    resources :static_pages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/:page' => 'static_pages#show'

  

end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id          :integer          not null, primary key
#  title       :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Gallery < ActiveRecord::Base
  has_many :gallery_images, inverse_of: :gallery, dependent: :destroy
  accepts_nested_attributes_for :gallery_images, allow_destroy: true, reject_if: :all_blank # Ignore the blank template record
  validates :title, presence: true

  def to_param
    slug
  end
end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::BaseController
  before_action :set_gallery, only: %i(show edit update destroy)

  def index
    @galleries = Gallery.all.order("published_at DESC").paginate(page: params[:page], per_page: 20)
  end

  def new
    @gallery = Gallery.new
  end

  def edit
  end

  def destroy
    @gallery.delete
    redirect_to admin_galleries_path
  end

  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.slug = @gallery.title.parameterize
    if @gallery.save
      flash[:notice] = "Your gallery has been created."
      redirect_to admin_galleries_path
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  def update
    @gallery.assign_attributes(gallery_params)
    @gallery.slug = @gallery.title.parameterize
    if @gallery.save
      flash[:notice] = "Your gallery has been created."
      redirect_to admin_galleries_path
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def set_gallery
    @gallery = Gallery.find_by slug: params[:slug]
  end

  def gallery_params
    params.require(:gallery).permit(:title, :published_at, :description)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: %i(show edit update destroy)

  def index
    @galleries = Gallery.all.paginate(page: params[:page], per_page: 10).order('published_at DESC')
  end


  def show
  end

  private

  def set_gallery
    @gallery = Gallery.find_by slug: params[:slug]
  end
end

app/views/admin/galleries/_form.html.erb
<div class="card-panel">
<%= form_for [:admin, @gallery], html: { multipart: true } do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <script>
      M.toast({html: $("#error_explanation").html()});
    </script>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.date_field :published_at, value: @gallery&.published_at.nil? ? Date.today : @gallery.published_at.to_date, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control mb-4" %>
  </div>
  <% if @gallery.id %>
  <%= link_to admin_gallery_gallery_images_path(@gallery) do %>
    <div class="btn btn-primary">
      <span>Edit Images</span>
    </div>
  <% end %>
  <% end %>
  <div id='gallery_images' class='flex-container'>
    <%= render @gallery.gallery_images %>
  </div>
  <br>
  <button class="btn btn-primary btn-block btn-lg mb-4" type="submit" name="action">SUBMIT <i class="fas fa-paper-plane ml-1"></i></button>
<% end %>
</div>

app/views/admin/galleries/_gallery_image.html.erb
<% unless gallery_image.new_record?%>
<div class="card image-container hoverable">
  <div class="card-image">
    <%= image_tag(gallery_image.image.thumb.url, class: 'gallery-image-thumbnail') unless gallery_image.image.nil? %>
  </div>
  <div class="card-action">
    <%= link_to "Delete", admin_gallery_gallery_image_path(gallery_image.gallery, gallery_image), data: {:confirm => 'Are you sure?'}, method: :delete %>
  </div>
</div>
<% end %>

app/views/admin/galleries/edit.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_galleries_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">Edit Galeri </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>

app/views/admin/galleries/index.html.erb
<div class="card single-card">  
  <div class="card-body m-0">
    <div class="d-flex justify-content-between">
      <%= link_to admin_root_path, class:'btn dark-gradient' do %>
        <i class="material-icons left">arrow_back</i>Back
      <% end%>
      <h2 class="float-none text-center"> Galeri </h2>
      <%= link_to 'New gallery', new_admin_gallery_path, class:'btn dark-gradient' %>
    </div>
    <div class="table-responsive text-nowrap">
      <table class="table ">
        <thead class="dark-gradient">
          <tr>
            <th>Title</th>
            <th colspan="3" class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @galleries.each do |gallery| %>
            <tr>
              <td><%= gallery.title %></td>
              <td class="text-center"><%= link_to 'Show', gallery, class: "btn btn-link " %></td>
              <td class="text-center"><%= link_to 'Edit', edit_admin_gallery_path(gallery), class: "btn btn-link" %></td>
              <td class="text-center"><%= link_to 'Destroy', [:admin, gallery], class: "btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <div>
    <div class="center">
        <%= will_paginate @galleries, renderer: @custom_paginate_renderer %>
    </div>
  </div>
</div>

app/views/admin/galleries/new.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_galleries_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">New Galeri </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>