config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :videos, only: [:show, :index], param: :slug
  resources :events, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :comments, only: [:show, :index] do
    resources :comments, only: [:show, :index, :create]
  end
  resources :galleries, only: [:show, :index], param: :slug
  resources :employees, only: :index
  root 'posts#home'
  get '/blog' => 'posts#index'
  get '/team' => 'employees#index'

  namespace :admin do
    root 'dashboards#index'
    resources :galleries, param: :slug do
      resources :gallery_images
    end
    resources :events, param: :slug do
      resources :comments
    end
    resources :categories
    resources :posts, param: :slug do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
    resources :users
    resources :videos, param: :slug
    resources :galleries, param: :slug
    resources :employees
    resources :static_pages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/:page' => 'static_pages#show'

  

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  summary    :string
#  thumbnail  :string
#  gallery_id :integer
#

class Event < ActiveRecord::Base
  self.per_page = 10
  belongs_to :category
  belongs_to :gallery
  has_many :comments, as: :commentable
  mount_uploader :thumbnail, ThumbnailUploader

  scope :by_category, -> (category_name) do
    joins(:category).where(categories: { name: category_name })
  end
  scope :search, -> (search) do
    where('title ILIKE lower(?) OR body ILIKE lower(?)', "%#{search}%", "%#{search}%" )
  end

  def to_meta_tags
    {
      title: title,
      image_src: thumbnail.thumb.url,
      og: {
        title: title,
        type: 'article',
        image: thumbnail.thumb.url
      }
    }
  end

  def to_param
    slug
  end

  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :set_event, only: %i(show edit update destroy)

  # GET /posts
  # GET /posts.json
  def index
    @events = Event.all.order("published_at DESC").paginate(page: params[:page], per_page: 20)
  end

  # GET /posts/1
  # GET /posts/1.json

  def show; end

  # GET /posts/new
  def new
    @event = Event.new
  end

  # GET /posts/1/edit

  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @event = Event.new(event_params)
    @event.slug = @event.title.parameterize
    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_events_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    @event.assign_attributes(event_params)
    @event.slug = @event.title.parameterize
    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_events_url, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find_by slug: params[:slug]
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  def event_params
    params.require(:event).permit(:title, :published_at, :summary, :body, :gallery_id, :category_id, :thumbnail)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i(show edit update destroy)

  def index
    @form_url = events_path
    @search_url = events_path(search: params[:search])
    @tag_urls = {}
    @events = get_events
    @categories = Category.event
    for category in @categories
      @tag_urls[category.name] = events_path(category: category.name, search: params[:search])
    end
  end

  def show
    set_meta_tags @event
  end

  private

  def get_events(category=params[:category], search=params[:search])
    if category.blank? && search.blank?
      events = Event.all
    elsif category.blank? && search.present?
      events = Event.search(search)
    elsif category.present? && search.blank?
      events = Event.by_category(category)
    elsif category.present? && search.present?
      events = Event.by_category(category).search(search)
    end
    events.paginate(page: params[:page], per_page: 10).order('published_at DESC')
  end

  def set_event
    @event = Event.find_by slug: params[:slug]
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  def event_params
    params.require(:event).permit(:title, :summary, :body, :gallery_id, :thumbnail)
  end
end

app/views/admin/events/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url%>
<div class="card-panel">
<%= form_for([:admin, @event]) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <ul>
      <li><h6><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h6></li>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <script>
      M.toast({html: $("#error_explanation").html()});
    </script>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.date_field :published_at, value: @event&.published_at.nil? ? Date.today : @event.published_at.to_date, class: "form-control mb-4" %>
  </div>
  <div class="input-field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.event, :id, :name, {}, class: 'browser-default custom-select mb-4') %>
  </div>
  <div class="input-field">
    <%= f.label :gallery_id %><br>
    <%= f.collection_select(:gallery_id, Gallery.all, :id, :title, {}, class: 'browser-default custom-select mb-4', include_blank: true) %>
  </div>
  <%= image_tag(@event.thumbnail.thumb.url, class: 'img_prev mb-4', style: ('display:none;' if @event.thumbnail.nil? )) %>
  <div class="custom-file mb-4">
    <%= f.file_field :thumbnail, onchange: 'image_preview(this);', class: 'custom-file-input' %>
    <label class="custom-file-label" for="customFile">Choose file</label>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary, class: "form-control", id: "summary-textarea", data: { length: 300 }, placeholder: "Write the event summary here" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, class: 'someclass', rows: 40, ckeditor: { language: 'us' } %>
  </div>
  <br>
  <button class="btn btn-primary btn-block btn-lg mb-4" type="submit" name="action">SUBMIT <i class="fas fa-paper-plane ml-1"></i></button>
<% end %>
</div>
<script>
$('textarea#summary-textarea').characterCounter();
</script>

app/views/admin/events/edit.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_events_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">Edit Event </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>

app/views/admin/events/index.html.erb
<div class="card single-card">  
  <div class="card-body m-0">
    <div class="d-flex justify-content-between">
      <%= link_to admin_root_path, class:'btn dark-gradient' do %>
        <i class="material-icons left">arrow_back</i>Back
      <% end%>
      <h2 class="float-none text-center"> events </h2>
      <%= link_to 'New event', new_admin_event_path, class:'btn dark-gradient' %>
    </div>
    <div class="table-responsive text-nowrap">
      <table class="table ">
        <thead class="dark-gradient">
          <tr>
            <th>Title</th>
            <th colspan="3" class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.title %></td>
              <td class="text-center"><%= link_to 'Show', event, class: "btn btn-link " %></td>
              <td class="text-center"><%= link_to 'Edit', edit_admin_event_path(event), class: "btn btn-link" %></td>
              <td class="text-center"><%= link_to 'Destroy', [:admin, event], class: "btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <div>
    <div class="center">
        <%= will_paginate @events, renderer: @custom_paginate_renderer %>
    </div>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_events_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">New Event </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>