config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :videos, only: [:show, :index], param: :slug
  resources :events, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :comments, only: [:show, :index] do
    resources :comments, only: [:show, :index, :create]
  end
  resources :galleries, only: [:show, :index], param: :slug
  resources :employees, only: :index
  root 'posts#home'
  get '/blog' => 'posts#index'
  get '/team' => 'employees#index'

  namespace :admin do
    root 'dashboards#index'
    resources :galleries, param: :slug do
      resources :gallery_images
    end
    resources :events, param: :slug do
      resources :comments
    end
    resources :categories
    resources :posts, param: :slug do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
    resources :users
    resources :videos, param: :slug
    resources :galleries, param: :slug
    resources :employees
    resources :static_pages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/:page' => 'static_pages#show'

  

end

app/models/employee.rb
# == Schema Information
#
# Table name: employees
#
#  id          :integer          not null, primary key
#  name        :string
#  position    :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string
#  sort        :integer
#

class Employee < ActiveRecord::Base
  include RailsSortable::Model
  set_sortable :sort
  mount_uploader :image, EmployeeImageUploader
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < Admin::BaseController
  before_action :set_employee, only: %i(show edit update destroy)

  def index
    @employees = Employee.order(:sort).all.paginate(page: params[:page], per_page: 20)
  end

  def new
    @employee = Employee.new
  end

  def edit; end

  def destroy
    @employee.delete
    redirect_to admin_employees_path
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to admin_employees_url, notice: 'employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @employee.update_attributes(employee_params)
        format.html { redirect_to admin_employees_url, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:name, :position, :image, :sort)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.order(:sort).all.paginate(page: params[:page], per_page: 20)
  end
end

app/views/admin/employees/_form.html.erb
<%= form_for([:admin, @employee]) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <script>
      M.toast({html: $("#error_explanation").html()});
    </script>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :sort %><br>
    <%= f.text_field :sort, class: "form-control mb-4" %>
  </div>
  <%= image_tag(@employee.image_url, class: "img_prev mb-4", style: ('display:none;' if @employee.image_url.nil? )) %>
  <div class="custom-file mb-4">
    <%= f.file_field :image, id: "image-field", onchange: 'image_preview(this, 150, 200);', class: 'custom-file-input' %>
    <label class="custom-file-label" for="customFile">Choose file</label>
  </div>
  <br>
  <button class="btn btn-primary btn-block btn-lg mb-4" type="submit" name="action">SUBMIT <i class="fas fa-paper-plane ml-1"></i></button>
<% end %>

app/views/admin/employees/edit.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_employees_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">Edit Staff </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>

app/views/admin/employees/index.html.erb
<div class="card single-card">  
  <div class="card-body m-0">
    <div class="d-flex justify-content-between">
      <%= link_to admin_root_path, class:'btn dark-gradient' do %>
        <i class="material-icons left">arrow_back</i>Back
      <% end%>
      <h2 class="float-none text-center"> Staffs </h2>
      <%= link_to 'New employee', new_admin_employee_path, class:'btn dark-gradient' %>
    </div>
    <div class="table-responsive text-nowrap">
      <table class="table ">
        <thead class="dark-gradient">
          <tr>
            <th>Name</th>
            <th>Position</th>
            <th colspan="3" class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @employees.each do |employee| %>
            <tr id="<%= employee.sortable_id %>">
              <td><%= employee.name %></td>
              <td><%= employee.position %></td>
              <td class="text-center"><%= link_to 'Show', employees_path, class: "btn btn-link " %></td>
              <td class="text-center"><%= link_to 'Edit', edit_admin_employee_path(employee), class: "btn btn-link" %></td>
              <td class="text-center"><%= link_to 'Destroy', [:admin, employee], class: "btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <div>
    <div class="center">
        <%= will_paginate @employees, renderer: @custom_paginate_renderer %>
    </div>
  </div>
</div>

app/views/admin/employees/new.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_employees_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">New Staff </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>