config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :posts, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :videos, only: [:show, :index], param: :slug
  resources :events, only: [:show, :index], param: :slug do
    resources :comments, only: [:show, :index, :create]
  end
  resources :comments, only: [:show, :index] do
    resources :comments, only: [:show, :index, :create]
  end
  resources :galleries, only: [:show, :index], param: :slug
  resources :employees, only: :index
  root 'posts#home'
  get '/blog' => 'posts#index'
  get '/team' => 'employees#index'

  namespace :admin do
    root 'dashboards#index'
    resources :galleries, param: :slug do
      resources :gallery_images
    end
    resources :events, param: :slug do
      resources :comments
    end
    resources :categories
    resources :posts, param: :slug do
      resources :comments
    end
    resources :comments do
      resources :comments
    end
    resources :users
    resources :videos, param: :slug
    resources :galleries, param: :slug
    resources :employees
    resources :static_pages
  end

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/:page' => 'static_pages#show'

  

end

app/models/video.rb
class Video < ActiveRecord::Base
  validates :title, presence: true

  def to_meta_tags
    {
      title: title,
      image_src: thumbnail,
      og: {
        title: title,
        video: 'https://www.youtube.com/v/'+youtube_id,
        image: thumbnail,
      }
    }
  end

  def to_param
    slug
  end
end

app/controllers/admin/videos_controller.rb
class Admin::VideosController < Admin::BaseController
  before_action :set_video, only: %i(show edit update destroy)

  # GET /posts
  # GET /posts.json
  def index
    @videos = Video.all.order("published_at DESC").paginate(page: params[:page], per_page: 20)
  end

  # GET /posts/1
  # GET /posts/1.json

  def show
  end

  # GET /posts/new
  def new
    @video = Video.new
  end

  # GET /posts/1/edit

  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @video = Video.new(video_params)
    @video.youtube_id = youtube_id(@video.youtube_url)
    @video.slug = @video.title.parameterize
    @video.thumbnail = "https://img.youtube.com/vi/"+@video.youtube_id+"/hqdefault.jpg"
    respond_to do |format|
      if @video.save
        format.html { redirect_to admin_videos_url, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      @video.assign_attributes(video_params)
      @video.slug = @video.title.parameterize
      @video.youtube_id = youtube_id(@video.youtube_url)
      @video.thumbnail = "https://img.youtube.com/vi/"+@video.youtube_id+"/hqdefault.jpg"
      if @video.save
        format.html { redirect_to admin_videos_url, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to admin_videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


  def youtube_id(youtube_url)
    regex = /(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/
    match = regex.match(youtube_url)
    if match && !match[1].blank?
      match[1]
    else
      nil
    end
  end
  # Use callbacks to share common setup or constraints between actions.

  def set_video
    @video = Video.find_by slug: params[:slug]
  end
  # Never trust parameters from the scary internet, only allow the white list through.

  def video_params
    params.require(:video).permit(:title, :body, :user_id, :published_at, :thumbnail, :youtube_url, :youtube_id)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all.paginate(page: params[:page], per_page: 20).order("published_at DESC")
  end

  def show
    @video = Video.find_by slug: params[:slug]
    set_meta_tags @video
  end
end

app/views/admin/videos/_form.html.erb
<%= form_for([:admin, @video]) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <ul>
      <li><h6><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h6></li>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <script>
      M.toast({html: $("#error_explanation").html()});
    </script>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :youtube_url %><br>
    <%= f.text_field :youtube_url, class: "form-control mb-4" %>
  </div>
  <div class="field">
    <%= f.label :published_at %><br>
    <%= f.date_field :published_at, value: @video&.published_at.nil? ? Date.today : @video.published_at.to_date, class: "form-control mb-4" %>
  </div>
  <%= image_tag(@video.thumbnail, class: 'img_prev mb-4', style: ('display:none;' if @video.thumbnail.nil? )) %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.cktext_area :body, class: 'someclass', rows: 40, ckeditor: { language: 'us' } %>
  </div>
  <br>
  <button class="btn btn-primary btn-block btn-lg mb-4" type="submit" name="action">SUBMIT <i class="fas fa-paper-plane ml-1"></i></button>
<% end %>

app/views/admin/videos/edit.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_videos_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">Edit Video </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>

<%= javascript_include_tag Ckeditor.cdn_url%>

app/views/admin/videos/index.html.erb
<div class="card single-card">  
  <div class="card-body m-0">
    <div class="d-flex justify-content-between">
      <%= link_to admin_root_path, class:'btn dark-gradient' do %>
        <i class="material-icons left">arrow_back</i>Back
      <% end%>
      <h2 class="float-none text-center"> Videos </h2>
      <%= link_to 'New video', new_admin_video_path, class:'btn dark-gradient' %>
    </div>
    <div class="table-responsive text-nowrap">
      <table class="table ">
        <thead class="dark-gradient">
          <tr>
            <th>Title</th>
            <th colspan="3" class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @videos.each do |video| %>
            <tr>
              <td><%= video.title %></td>
              <td class="text-center"><%= link_to 'Show', video, class: "btn btn-link " %></td>
              <td class="text-center"><%= link_to 'Edit', edit_admin_video_path(video), class: "btn btn-link" %></td>
              <td class="text-center"><%= link_to 'Destroy', [:admin, video], class: "btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <div>
    <div class="center">
        <%= will_paginate @videos, renderer: @custom_paginate_renderer %>
    </div>
  </div>
</div>

app/views/admin/videos/new.html.erb
<div class="card single-card">
  <div class="card-body">
    <div class="d-flex justify-content-between">
      <%= link_to admin_videos_path, class:'btn dark-gradient' do %>
        <i class="fas fa-arrow-left"></i> Back
      <% end%>
      <h2 class="float-none text-center">New Video </h2>
      <div></div>
    </div>
  <br>
  <%= render 'form' %>
  </div>
</div>

<%= javascript_include_tag Ckeditor.cdn_url%>